@startuml

object artifact
artifact : id = INT
artifact : name = VARCHAR(50)
artifact : created = DATETIME
artifact : updated = DATETIME


object codex_category
codex_category : id = INT
codex_category : artifact_id = INT
codex_category : name = VARCHAR(50)
codex_category : created = DATETIME
codex_category : updated = DATETIME

codex_category "0..1" -- "1" artifact


object codex_data
codex_data : id = INT
codex_data : category_id, INT
codex_data : entry_number = INT
codex_data : artifact_id = INT
codex_data : text = TEXT
codex_data : created = DATETIME
codex_data : updated = DATETIME

codex_data "1..n" -- "1" codex_category
codex_data "0..n" -- "0..1" artifact

object ruin_type
ruin_type : id = INT
ruin_type : name = VARCHAR(50)
ruin_type : created = DATETIME
ruin_type : updated = DATETIME


object obelisk_group
obelisk_group : id = INT
obelisk_group : ruintype_id = INT
obelisk_group : name = VARCHAR(50)
obelisk_group : count = INT
obelisk_group : created = DATETIME
obelisk_group : updated = DATETIME

obelisk_group "0..n" -- "1" ruin_type


object obelisk
obelisk : id = INT
obelisk : obeliskgroup_id = INT
obelisk : number = INT
obelisk : is_broken = BOOL
obelisk : is_verified = BOOL
obelisk : codexdata_id = INT
obelisk : created = DATETIME
obelisk : updated = DATETIME

obelisk "1..n" -- "1" obelisk_group
obelisk "0..1" -- "0..1" codex_data


object system
system : id = INT
system : name = VARCHAR(150)
system : edsm_coord_x = FLOAT
system : edsm_coord_y = FLOAT
system : edsm_coord_z = FLOAT
system : edsm_coord_updated = DATETIME
system : edsm_ext_id = INT (id from EDSM)
system : eddb_ext_id = INT (id from EDDB)
system : created = DATETIME
system : updated = DATETIME


object body
body : id = INT
body : system_id = INT
body : name = VARCHAR(150)
body : distance = INT (from EDSM)
body : edsm_ext_id = INT (id from EDSM)
body : eddb_ext_id = INT (id from EDDB)
body : created = DATETIME
body : updated = DATETIME

body "0..n" -- "1" system


object ruin_site
ruin_site : id = INT
ruin_site : body_id = INT
ruin_site : latitude = DECIMAL(6,4)
ruin_site : longitude = DECIMAL(7,4)
ruin_site : ruintype_id = INT
ruin_site : created = DATETIME
ruin_site : updated = DATETIME

ruin_site "0..n" -- "1" body
ruin_site "0..n" -- "1" ruin_type


object ruinsite_obeliskgroups
ruinsite_obeliskgroups : ruinsite_id = INT
ruinsite_obeliskgroups : obeliskgroup_id = INT

ruinsite_obeliskgroups "0..n" -- "1" ruin_site
ruinsite_obeliskgroups "0..n" -- "1" obelisk_group


object ruinsite_activeobelisks
ruinsite_activeobelisks : ruinsite_id = INT
ruinsite_activeobelisks : obelisk_id = INT

ruinsite_activeobelisks "0..n" -- "1" ruin_site
ruinsite_activeobelisks "0..n" -- "1" obelisk

@enduml